### ISSUE TITLE
Incorporation of `fit_intercept` to `LinearRegression`?

### ISSUE THREAD

**Issue by MattWenham** [abess-team/abess#507] opened 2023-05-09 13:49 UTC
Would it be possible to introduce a `fit_intercept` to `LinearRegression`, similar to the sklearn linear regression implementation?

**Comment by Mamba413** [comment] 2023-05-10 06:47
Thank you for your question. I’m not sure why `sklearn.linear_model. LinearRegression` includes a `fit_intercept` parameter. For instance, if someone sets `fit_intercept=False` but forgets to center the response, the parameter estimation will be inaccurate: 
```python
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
# y = 1 * x_0 + 2 * x_1 + 3
y = np.dot(X, np.array([1, 2])) + 3
reg = LinearRegression().fit(X, y)
reg.coef_
>>> array([1., 2.])
reg = LinearRegression(fit_intercept=False).fit(X, y)
reg.coef_
>>> array([2.09090909, 2.54545455])
```
In my personal opinion, the `fit_intercept` parameter is unnecessary. Perhaps I’m missing something. Could you provide some reasoning for including this parameter?

**Comment by MattWenham** [comment] 2023-05-11 13:41
An obvious example is the curve-fitting of basis functions to observations. 

![image](https://github.com/abess-team/abess/assets/14311212/73f57f26-dca0-47c5-b5b2-598025cee828)
Here, we fit a set of observations S to two sets of basis functions: the **μ** are the foreground basis functions from which we need to choose, hence using `abess`. The **B** are the background basis functions, which are `always_select`ed. There is no intercept term in this least-squares fit.

**Comment by Mamba413** [comment] 2023-05-19 06:30
Thanks. I also notice that generalized linear models, like `LogisticRegression` (https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html) and `PoissonRegressor` (https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.PoissonRegressor.html), also support`fit_intercept`. It seems this parameter is practically helpful, and we will implement this soon.

**Comment by MattWenham** [comment] 2023-05-19 09:23
Thank you for your responsiveness!

**Closed** 2023-06-09 02:41 UTC
Labels: enhancement

**Comment by Mamba413** [comment] 2023-06-09 02:48
@MattWenham , hi, we have just implemented this feature. Beyond, `fit_intercept` is also supported by `LogisticRegression`, `PoissonRegression` and other generalized linear modes. You can install the latest version of `abess` (see https://abess.readthedocs.io/en/latest/Installation.html#python-1) to use this new feature.

**Comment by Mamba413** [comment] 2023-06-10 02:57
According to the results of `pip list`, the version of `pybind11` is:
```shell
pybind11                      2.9.1
pybind11-global               2.9.1
```
Maybe the issue appears because `pybind11-global` hasn't been installed? You can install this via:
`pip install "pybind11[global]"`. 

Wish that helps!

**Comment by MattWenham** [comment] 2023-06-13 08:53
We have downgraded to `pybind11` 2.9.1:

    pybind11                  2.9.1                    pypi_0    pypi
    pybind11-global           2.9.1                    pypi_0    pypi

...and continue to get the same error. We are attempting to install under WSL / Ubuntu 22.04.1 LTS.

**Comment by oooo26** [comment] 2023-06-16 05:57
Hi @MattWenham , we have tried `pybind11` 2.9.1 & 2.10.4(latest release), and both of them work to build `abess`. 

Could you check if there is multiple python environment in the device and then `pybind11` may be installed to another environment? Or try a new conda environment(python version >= 3.6)?

If the error still exists, please paste more error logs here so that we can help to solve it.
